[project]
channels = ["conda-forge"]
description = "Course Materials for BINF 5507"
name = "BINF-5507-caryngeady"
platforms = ["osx-arm64","osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.1.3,<3"
matplotlib = ">=3.9.3,<4"
scikit-learn = ">=1.5.2,<2"
pip = ">=24.3.1,<25"
ipykernel = ">=6.29.5,<7"
seaborn = ">=0.13.2,<0.14"
ipywidgets = ">=8.1.5,<9"
