[project]
authors = ["cgeady <caryn@geady.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "BINF-5507-caryngeady"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.1.3,<3"
matplotlib = ">=3.9.2,<4"
pip = ">=24.3.1,<25"
ipykernel = ">=6.29.5,<7"
scikit-learn = ">=1.5.2,<2"
pandas = ">=2.2.3,<3"
seaborn = ">=0.13.2,<0.14"
